spring.datasource.url=jdbc:postgresql://localhost:5432/tourplanner
spring.datasource.username=postgres
spring.datasource.password=deinpasswort
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update