spring.datasource.url=jdbc:postgresql://localhost:5432/tourlogdb
spring.datasource.username=tourlog_user
spring.datasource.password=tourlog_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# OpenRouteService — get a free key at https://openrouteservice.org
ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjhiNTM2ZTk5OGRhNzQ0NGNiNTUyOTBmMzE2YTEwMmM2IiwiaCI6Im11cm11cjY0In0=
ors.api.base-url=https://api.openrouteservice.org
